# Generated by Django 3.1.6 on 2021-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletfunding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='walletwithdrawal',
            name='user',
        ),
        migrations.AddField(
            model_name='walletfunding',
            name='email',
            field=models.CharField(default='ade@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='walletfunding',
            name='fullname',
            field=models.CharField(default='bUZI aWOBADE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletwithdrawal',
            name='email',
            field=models.CharField(default='ade@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='walletwithdrawal',
            name='fullname',
            field=models.CharField(default='BUZI AWOBADE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletfunding',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walletwithdrawal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
