# Generated by Django 3.1.6 on 2021-02-26 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210226_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 7, 15, 16, 644088)),
        ),
    ]
