# Generated by Django 3.1.6 on 2021-02-27 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20210227_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 27, 17, 53, 31, 883625)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 17, 53, 31, 883625)),
        ),
    ]
