# Generated by Django 3.1.6 on 2021-03-18 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20210304_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 18, 7, 55, 1, 827772)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 7, 55, 1, 827772)),
        ),
    ]
