# Generated by Django 3.1.6 on 2021-02-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor2',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctor2',
            name='wallet_balance',
        ),
    ]
