# Generated by Django 3.1.6 on 2021-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210224_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor2',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
