# Generated by Django 3.1.6 on 2021-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor2_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbalance',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorModel',
        ),
        migrations.DeleteModel(
            name='WalletBalance',
        ),
    ]
